from enum import Enum

class Icons(Enum):
    POWER = ""
    LOGOUT = "󰗽"
    REBOOT = ""
    SLEEP = "󰤄"
    CPU = " "
    MEM = " "
    BOOST = "󱀚 "
    BAT = " "
    CHARGING = ""
    MEDIA_PREV = "󰒮"
    MEDIA_PLAY = "󰐊"
    MEDIA_PAUSE = "󰏤"
    MEDIA_REPEAT = "󰑖"
    MEDIA_NEXT = "󰒭"
    VOL = ""
    VOL_MUTE = ""
    BRIGHTNESS = "󱄄"
    TEMP = "󰔏"
    PIC = "󱧾"
    SEND = ""
    LAUNCHER = "󱈇"
    SETTINGS = ""
    TERM = ""
    BROWSER = "󰖟"
    FILES = ""
    NOTES = "󰠮"
    EDITOR = ""
    MUSIC = ""
    WIFI = "󰤨"
    BLUETOOTH = "󰂯"
    NOTIFICATIONS = ""
    DISK = "󱛟"
    STOPWATCH = ""
    CALENDAR = "󰃭"

    


